finfine|at last, at long last
influo|influence
inter|among, between
klare|clearly
korpo|body
makabra|macabre
malhela|bleak, dark, dismal, dreary
maniero|manner, mode, way
mem|self, herself, himself, itself
neniam|never
nomi|call
pasia|passionate
potenco|power
povi|be able to
tia|such, such a, that kind of
unua|first
antikva|ancient, antique
aŭskulti|listen
bildo|image, picture
domego|mansion
drako|dragon
fenestro|window
formo|form, shape
jaro|year
kial|why
konstruaĵo|building
lasta|last
libro|book
lumo|light
nokto|night
pala|pale, sallow
percepti|find, notice, perceive
planko|floor
priskribi|describe
sendube|no doubt, undoubtedly
stari|stand
stato|condition, state
tempo|time, while
vin|you
vojo|road, route, way
ŝanĝiĝo|alteration, change, conversion, transformation
ŝildo|shield, sign-board
aldone|in addition
aparta|apart, particular, separate, special
apenaŭ|barely, hardly, only just, scarcely
aspekto|appearance, aspect
baldaŭ|soon
certe|certainly
cetere|besides, for the rest, moreover, what's more
delikata|dainty, delicate, fine, refined
deziro|desire, want, wish
efekto|effect, impression
ekzisto|existence
estigi|develop
familia|domestic
hasta|hurried
ho|oh
intensa|intense, intensive
kondiĉo|condition, stipulation, terms
krom|apart from, besides, except, except for
mieno|expression
nova|new, novel
ofte|frequently, often, regularly
okulo|eye
opinio|opinion
periodo|period
peza|burdensome, heavy, onerous
rakonto|narrative, story, tale
silenta|silent
simpla|simple, straightforward
stranga|odd, peculiar, strange
verŝajne|probably
ĉiam|always, ever
abrupta|abrupt
aranĝi|arrange, fix up
arĝento|silver
atento|attention
atingi|accomplish, attain, get, reach
barakti|flounder, struggle, writhe
bela|beautiful, fine, handsome, lovely
bieno|estate, farm, property, ranch
bone|OK, okay, well
ermito|hermit
facile|easily
familio|family
fluo|current, flow, stream
griza|grey
homa|human
kelo|basement, cellar
knabeca|boyish
konkludi|abstract, induce, gather, infer
konstanta|constant, continual, permanent, sustained
koro|heart
letero|letter
loĝejo|abode, accommodation, dwelling, residence
malĝojo|sadness, sorrow
mencii|mention
natura|natural
palaco|palace
persona|personal
pligrandigi|augment, enlarge, increase
profunda|deep, profound
seninterrompa|continuous
senĉesa|constant, lasting, sustained
severa|severe, strict
speco|kind, sort
taksi|appraise, estimate, rate
tial|therefore
tiam|then
ĉerko|coffin
ŝtona|metalled, stone
ŝtuparo|staircase, stairs
aero|air
amara|bitter
animo|soul
ankaŭ|also, likewise, too
beleco|beauty
brila|bright, brilliant
bruo|ado, din, noise
celo|aim, goal, purpose
direkto|direction
distanco|distance, offset
dormi|be asleep, sleep
eksciti|excite
ekscitiĝo|excitement
etoso|atmosphere, ethos, mood
feliĉa|fortunate, happy
fero|iron
fizika|physical
foje|once, on occasion, sometimes
foriri|absent onself, depart, go away, leave
freneza|crazy, insane, mad, nuts
gento|race, people
gloro|fame, glory, renown
hororo|horror
imago|imagination
interesi|interest
interne|inside
intima|close, intimate
jene|thus
kapo|head, pate
karcero|cell
kiom|how many, how much
klopodo|attempt, effort
komento|comment
konservi|conserve, keep, maintain, preserve
kontraŭ|across from, against, in exchange for, opposed to, opposite, upon
kontraŭstari|confront, stand up to, withstand
kredi|believe, deem
kreski|grow
larĝa|broad
malica|malicious, mischievous, nasty, vicious
mastro|boss, master
morna|desolate, dismal, dreary, gaunt, gloomy, mournful
morto|death
nervoza|nervous
paŝo|pace, step, stride
pentraĵo|painting, picture
perforte|by force, violently
peti|ask, ask for, beg, bid, request
pordego|gate, gateway, portal
proksime|close, near, nearby
regiono|region
rideto|smile
rimarkinda|noteworthy, remarkable
sceno|scene
seĝo|chair
sincera|above-board, sincere
spirado|respiration
sufiĉe|enough, quite, rather, sufficiently
superstiĉo|superstition
tegmento|roof
timo|fear
tuŝo|touch
valo|valley
vasta|extensive, spacious, vast, wide
verko|work
vespero|evening
vojaĝo|journey, trip, voyage
voĉo|voice, vote
ĉevalo|horse
ĉielo|heaven, sky
ĝenerala|general, usual
akcesora|accessory, secondary
almenaŭ|at least
alproksimiĝi|advance, come close, come closer, come on
alveno|arrival
amata|loved, beloved
anstataŭe|instead
arda|ablaze, ardent
artefarita|artificial
atmosfero|atmosphere
bazo|base, basis
brusto|bosom, breast, chest
danĝero|danger, peril
denove|again, all over again, anew
desegnaĵo|design, drawing
ekscesa|excessive, inordinate
ekstera|external, outer, outside
ekvivalento|equivalent
eligi|draw out, drive out, express, utter, give utterance to, pull out
energia|energetic
energio|energy
enterigo|burial, funeral, interment
entute|altogether, as a whole, on the whole
fetora|bad-smelling, stinking, odorous
frenezulo|lunatic
frua|early
gitaro|guitar
grandega|enormous, huge, immense
hararo|hair
heziti|hesitate
internaĵo|inside
kompari|compare
komprenebla|understandable
konduto|behavior, behaviour, conduct, deportment
konvinko|belief, conviction
kriego|scream
kune|together
latuna|brass
legi|read
lito|bed
malkovri|discover, uncover
meblaro|furniture
melankolio|melancholy
melodio|melody, tune
mil|thousand, one thousand
mistika|mystic, mystical
monarko|monarch
morala|moral
nigra|black
nuligi|abjure, abolish, abrogate, annul, cancel, remit
odoro|odor, odour, scent, smell
oni|you, one, they
perfekta|perfect
plafono|ceiling
plaĉa|pleasing
plumba|lead
precipe|above all, especially, chiefly, mainly, principally
preciza|accurate, precise
procedo|procedure, process
propra|own, personal
raŭka|hoarse
reen|back, backwards
regno|realm, state
rekoni|recognise, recognize
rendevuo|appointment, date, rendezvous
rigida|rigid, stiff
rilate|as to, as regards, concerning
seka|dry
serioza|earnest, serious, staid
signifo|meaning
simileco|resemblance, similarity
situacio|circumstances, condition, situation
sonĝo|dream
supozi|guess, presume, suppose, surmise
supra|upper
surfaco|surface
surprizo|surprise
surtera|terrestrial
temperamento|temperament
torĉo|torch
trans|across, beyond, on the other side of
trudi|force, impose
tutaĵo|entirety
vane|in vain
vaporo|steam, vapor, vapour
verdire|to tell the truth
vigla|alert, brisk, keen
vigligi|encourage, stimulate
viro|fellow, man
volumo|volume
vualo|veil
zigzaga|zigzag
ĉampiono|champion
ĉeesto|presence
ĉefa|chief, main, major, principal
ĵeti|throw
abunda|abundant
afekcii|affect
akreco|sharpness
aliflanke|on the other hand
aliigi|alter, change, turn
almozo|alms
alparoli|address
alterne|alternately
amareco|bitterness
ambaŭ|both
ampleksi|comprise
analizo|analysis
ankoraŭ|still, yet
anomalia|deviating, divergent
antaŭzorgo|thoughtfulness
apatio|apathy
apud|at, beside, by, near, nearby, near to, next to
arto|art
aŭtuno|autumn
balado|ballad, ballade
bedaŭrinda|regrettable
bordo|bank, border, edge, shore
brava|brave, gallant
cerbo|brain
decido|decision
deponejo|depository
difektiĝi|break down
disde|out of
disiĝi|separate
disponebla|available
dolĉa|gentle, soft, sweet, tender
dominio|dominion
dua|second
dubi|doubt
ebriulo|drunk
efektivigita|completed
eklezio|church
eksperimento|experiment
ekspliki|explain
eksterordinara|extraordinary, formidable
elirejo|exit, way out
emocio|emotion
enlitigi|put to bed
enspiri|inhale
esprimi|express
estonteco|future
estro|boss, chief, leader
eviti|avoid, evade
fama|famous
farado|making, manufacture
fasado|facade, fa@ade
feroca|fierce
figuro|figure, diagram, image, picture, representation
filo|son
frazo|sentence
fulmo|lightning
gratuli|congratulate
grincado|grating
halo|hall
haŭto|skin
hebrea|Hebrew, Jewish
hereda|hereditary
heroo|hero
hezitado|hesitation, wavering
hipotezo|hypothesis
histerio|hysteria
historio|story, history
iam|at some time, ever, sometime
idaro|offspring
infero|hell
inkubo|incubus, nightmare
juneco|youth
kastelo|castle
kava|concave, hollow
kazo|afair, case, matter
